import { colleges } from "@/app/api/data";
import { College } from "@/types/college";
import { ScholarshipItem } from "@/types/scholarshipDiscovery";

export const scholarships: ScholarshipItem[] = [
  {
    name: "National Scholarship Portal (NSP) - Merit Cum Means",
    slug: "nsp-merit-cum-means",
    shortDescription: "Financial support for meritorious students from economically weaker sections.",
    provider: "Ministry of Education",
    providerType: "Central",
    scholarshipType: "Government",
    level: "UG",
    amountType: "Partial Funding",
    amountRange: [25000, 120000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Online",
    deadlineMonth: "October",
    renewable: true,
    popular: true,
    eligibility: {
      education: ["Class 12 pass", "Admission in approved UG/PG program"],
      minPercentage: "50%+ in previous qualifying exam",
      familyIncome: "Up to ₹2.5 Lakhs per annum",
      stateQuota: "Open across India",
      additional: ["Aadhaar linked bank account", "No duplicate scholarship claim"],
    },
    importantDates: [
      { label: "Application Start", month: "August", status: "Upcoming" },
      { label: "Application Deadline", month: "October", status: "Upcoming" },
      { label: "Verification", month: "November", status: "Upcoming" },
    ],
    benefits: [
      "Tuition fee support",
      "Maintenance allowance",
      "Direct Benefit Transfer (DBT)",
    ],
    requiredDocuments: [
      "Aadhaar card",
      "Income certificate",
      "Previous marksheet",
      "Institute verification form",
      "Bank passbook",
    ],
    applicationProcess: [
      "Register on NSP portal",
      "Complete profile and academic details",
      "Upload required documents",
      "Submit and track application status",
    ],
    selectionProcess: [
      "Merit and income-based screening",
      "Institute and nodal officer verification",
      "Final sanction and disbursement",
    ],
    preparationTips: [
      "Prepare documents before portal opens.",
      "Ensure bank details match Aadhaar records.",
      "Track institute verification deadlines.",
    ],
    faqs: [
      { question: "Can I apply every year?", answer: "Yes, if renewal criteria are met." },
      { question: "Is hard copy submission required?", answer: "Usually no, unless your institute asks." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["jawaharlal-nehru-university", "amity-university-jaipur", "gla-university-mathura"],
  },
  {
    name: "Post Matric Scholarship for SC Students",
    slug: "post-matric-sc",
    shortDescription: "Scholarship for SC students pursuing post-matric studies.",
    provider: "Ministry of Social Justice & Empowerment",
    providerType: "Central",
    scholarshipType: "Government",
    level: "Any",
    amountType: "Fee Waiver",
    amountRange: [18000, 150000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Online",
    deadlineMonth: "November",
    renewable: true,
    popular: true,
    eligibility: {
      education: ["Class 10 pass", "Admission in recognized institution"],
      minPercentage: "As per state/central guidelines",
      familyIncome: "Up to ₹2.5 Lakhs per annum",
      stateQuota: "State-wise allocation",
      additional: ["SC category certificate", "Domicile may be required"],
    },
    importantDates: [
      { label: "Application Window", month: "September-November", status: "Ongoing" },
      { label: "Institute Verification", month: "December", status: "Upcoming" },
    ],
    benefits: ["Tuition reimbursement", "Maintenance allowance", "Compulsory non-refundable fee support"],
    requiredDocuments: ["Caste certificate", "Income certificate", "Bonafide certificate", "Fee receipt"],
    applicationProcess: ["Apply via scholarship portal", "Submit institute details", "Attach proofs", "Track verification"],
    selectionProcess: ["Eligibility and category validation", "Income and document verification", "Fund release"],
    preparationTips: ["Use updated caste and income certificates.", "Keep fee receipts ready.", "Check state portal notices."],
    faqs: [
      { question: "Can private college students apply?", answer: "Yes, if institution is eligible under the scheme." },
      { question: "Is renewal automatic?", answer: "No, renewal application is generally required." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["dr-bhimrao-ambedkar-university", "dayalbagh-educational-institute", "st-johns-college-agra"],
  },
  {
    name: "AICTE Pragati Scholarship for Girls",
    slug: "aicte-pragati-girls",
    shortDescription: "Scholarship for girl students in technical education.",
    provider: "AICTE",
    providerType: "Central",
    scholarshipType: "Women",
    level: "UG",
    amountType: "Stipend",
    amountRange: [30000, 50000],
    applicationFee: 0,
    stream: "Engineering & Technical",
    mode: "Online",
    deadlineMonth: "December",
    renewable: true,
    popular: true,
    eligibility: {
      education: ["Admission in AICTE-approved diploma/degree institution"],
      minPercentage: "As per admission norms",
      familyIncome: "Up to ₹8 Lakhs per annum",
      stateQuota: "All India",
      additional: ["Maximum two girls per family (scheme norms apply)"],
    },
    importantDates: [
      { label: "Registrations", month: "October", status: "Upcoming" },
      { label: "Last Date", month: "December", status: "Upcoming" },
    ],
    benefits: ["Annual scholarship amount", "Support for technical education continuity"],
    requiredDocuments: ["Admission letter", "Income proof", "Aadhaar", "Bank details", "Bonafide certificate"],
    applicationProcess: ["Apply via NSP/AICTE scheme portal", "Fill institute and course details", "Upload proofs", "Submit"],
    selectionProcess: ["Merit and eligibility screening", "Institute validation", "Final allotment"],
    preparationTips: ["Check AICTE-approved institute list first.", "Submit early to avoid portal rush."],
    faqs: [
      { question: "Does it cover full tuition fee?", answer: "It provides fixed annual assistance, not always full fee." },
      { question: "Can diploma students apply?", answer: "Yes, eligible diploma students can apply under scheme rules." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["guru-gobind-singh-indraprastha-university", "gla-university-mathura", "amity-university-jaipur"],
  },
  {
    name: "INSPIRE Scholarship for Higher Education",
    slug: "inspire-she",
    shortDescription: "Scholarship for students pursuing natural and basic sciences.",
    provider: "DST, Government of India",
    providerType: "Central",
    scholarshipType: "Merit-Based",
    level: "UG",
    amountType: "Stipend",
    amountRange: [60000, 80000],
    applicationFee: 0,
    stream: "Science",
    mode: "Online",
    deadlineMonth: "November",
    renewable: true,
    popular: true,
    eligibility: {
      education: ["Top percentile in 12th board", "Enrolled in natural/basic sciences UG"],
      minPercentage: "Top 1% or equivalent eligibility route",
      familyIncome: "No strict cap in core criteria",
      stateQuota: "All India",
      additional: ["Not applicable for engineering/medicine streams"],
    },
    importantDates: [
      { label: "Portal Open", month: "September", status: "Upcoming" },
      { label: "Submission Deadline", month: "November", status: "Upcoming" },
    ],
    benefits: ["Annual scholarship amount", "Summer research mentorship opportunities"],
    requiredDocuments: ["Marksheets", "Admission proof", "Identity proof", "Bank details"],
    applicationProcess: ["Register on INSPIRE portal", "Complete profile", "Upload academic proofs", "Submit"],
    selectionProcess: ["Merit eligibility screening", "Document verification", "Approval and release"],
    preparationTips: ["Choose eligible science subjects only.", "Cross-check board percentile requirements."],
    faqs: [
      { question: "Can B.Tech students apply?", answer: "Generally no, INSPIRE SHE targets basic/natural sciences." },
      { question: "Is renewal performance-based?", answer: "Yes, continuation depends on academic progression." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["nalanda-university-delhi", "jawaharlal-nehru-university", "dayalbagh-educational-institute"],
  },
  {
    name: "KVPY (Legacy Track for Research Scholarships)",
    slug: "kvpy-legacy",
    shortDescription: "Research-oriented support pathway for science students (legacy reference for equivalents).",
    provider: "IISc / DST",
    providerType: "Central",
    scholarshipType: "Research",
    level: "Any",
    amountType: "Stipend",
    amountRange: [50000, 120000],
    applicationFee: 0,
    stream: "Science",
    mode: "Hybrid",
    deadlineMonth: "October",
    renewable: true,
    popular: false,
    eligibility: {
      education: ["Science stream students with strong academic track"],
      minPercentage: "As per notified program criteria",
      familyIncome: "No mandatory cap",
      stateQuota: "All India",
      additional: ["Research aptitude emphasis"],
    },
    importantDates: [
      { label: "Notification", month: "August", status: "Closed" },
      { label: "Assessment Window", month: "November", status: "Closed" },
    ],
    benefits: ["Scholarship stipend", "Mentorship and research exposure"],
    requiredDocuments: ["Academic records", "Identity proof", "Enrollment certificate"],
    applicationProcess: ["Register", "Submit academic profile", "Complete assessment/interview as applicable"],
    selectionProcess: ["Aptitude and merit-based selection", "Interview/screening"],
    preparationTips: ["Focus on science fundamentals.", "Practice analytical problem solving."],
    faqs: [
      { question: "Is KVPY still active in same format?", answer: "Candidates should check latest official announcements for current equivalent pathways." },
      { question: "Who should target this?", answer: "Students interested in pure science and research tracks." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["jawaharlal-nehru-university", "nalanda-university-delhi"],
  },
  {
    name: "Reliance Foundation Undergraduate Scholarship",
    slug: "reliance-foundation-ug",
    shortDescription: "Private merit-cum-need scholarship for undergraduate students.",
    provider: "Reliance Foundation",
    providerType: "Private",
    scholarshipType: "Private",
    level: "UG",
    amountType: "Partial Funding",
    amountRange: [50000, 200000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Online",
    deadlineMonth: "January",
    renewable: false,
    popular: true,
    eligibility: {
      education: ["First-year UG students"],
      minPercentage: "Merit-based shortlisting",
      familyIncome: "Need-based considerations applicable",
      stateQuota: "All India",
      additional: ["Aptitude test may be part of selection"],
    },
    importantDates: [
      { label: "Applications", month: "December", status: "Upcoming" },
      { label: "Assessment", month: "January", status: "Upcoming" },
    ],
    benefits: ["Tuition and academic support", "Mentor ecosystem access"],
    requiredDocuments: ["Identity proof", "Admission proof", "Academic records", "Income details"],
    applicationProcess: ["Apply on foundation portal", "Fill profile", "Take assessment if shortlisted", "Final selection"],
    selectionProcess: ["Merit + need evaluation", "Assessment and profile screening"],
    preparationTips: ["Keep statement of purpose concise and genuine.", "Highlight achievements and goals."],
    faqs: [
      { question: "Is it available for all colleges?", answer: "It is open to eligible students from recognized institutions." },
      { question: "Does it renew annually?", answer: "Program structure may vary by cycle; check latest guidelines." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["amity-university-jaipur", "gla-university-mathura", "guru-gobind-singh-indraprastha-university"],
  },
  {
    name: "HDFC Bank Parivartan's ECSS",
    slug: "hdfc-parivartan-ecss",
    shortDescription: "Need-based scholarship support for school to postgraduate levels.",
    provider: "HDFC Bank",
    providerType: "Private",
    scholarshipType: "Need-Based",
    level: "Any",
    amountType: "Partial Funding",
    amountRange: [15000, 75000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Online",
    deadlineMonth: "September",
    renewable: false,
    popular: true,
    eligibility: {
      education: ["School/UG/PG students in recognized institutions"],
      minPercentage: "55%+ in previous exam",
      familyIncome: "Usually up to ₹2.5 Lakhs (scheme-wise variations)",
      stateQuota: "All India",
      additional: ["Preference to students facing personal or financial crisis"],
    },
    importantDates: [
      { label: "Application Cycle", month: "July-September", status: "Ongoing" },
    ],
    benefits: ["Academic expense support", "Targeted need-based financial assistance"],
    requiredDocuments: ["Marksheets", "Income proof", "Crisis-related document (if applicable)", "Fee receipt"],
    applicationProcess: ["Register on partner scholarship platform", "Submit details and documents", "Await evaluation"],
    selectionProcess: ["Merit and need assessment", "Document and profile verification"],
    preparationTips: ["Provide accurate family income details.", "Upload clear document scans."],
    faqs: [
      { question: "Can gap-year students apply?", answer: "Depends on specific cycle terms." },
      { question: "Is interview mandatory?", answer: "Usually not, but screening calls may happen." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["dr-bhimrao-ambedkar-university", "st-johns-college-agra", "dayalbagh-educational-institute"],
  },
  {
    name: "Sitaram Jindal Foundation Scholarship",
    slug: "sitaram-jindal-scholarship",
    shortDescription: "Scholarship for economically weaker students across education levels.",
    provider: "Sitaram Jindal Foundation",
    providerType: "Private",
    scholarshipType: "Need-Based",
    level: "Any",
    amountType: "Stipend",
    amountRange: [5000, 52000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Hybrid",
    deadlineMonth: "Rolling",
    renewable: true,
    popular: false,
    eligibility: {
      education: ["Recognized course enrollment"],
      minPercentage: "As per category and course type",
      familyIncome: "Category-based thresholds",
      stateQuota: "All India",
      additional: ["Attendance and conduct requirements may apply"],
    },
    importantDates: [
      { label: "Applications", month: "Rolling", status: "Ongoing" },
    ],
    benefits: ["Monthly/periodic stipend", "Support till course completion (policy-based)"],
    requiredDocuments: ["Income proof", "Marksheet", "Bonafide certificate", "Photo and ID"],
    applicationProcess: ["Collect form from foundation/website", "Submit with documents", "Follow verification process"],
    selectionProcess: ["Need and merit-based consideration", "Document screening"],
    preparationTips: ["Apply early in course cycle.", "Follow document checklist strictly."],
    faqs: [
      { question: "Is this available every month?", answer: "The scheme usually runs continuously with periodic processing." },
      { question: "Can diploma students apply?", answer: "Yes, many diploma categories are included." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["gla-university-mathura", "dayalbagh-educational-institute", "dr-bhimrao-ambedkar-university"],
  },
  {
    name: "State Scholarship - Uttar Pradesh Post Matric",
    slug: "up-post-matric",
    shortDescription: "State-level scholarship for eligible post-matric students in Uttar Pradesh.",
    provider: "UP Scholarship Portal",
    providerType: "State",
    scholarshipType: "Government",
    level: "Any",
    amountType: "Fee Waiver",
    amountRange: [10000, 100000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Online",
    deadlineMonth: "December",
    renewable: true,
    popular: true,
    eligibility: {
      education: ["Resident of Uttar Pradesh", "Post-matric enrolled student"],
      minPercentage: "As per category/grade",
      familyIncome: "As per state norm",
      stateQuota: "Uttar Pradesh",
      additional: ["Domicile required", "Category certificate if applicable"],
    },
    importantDates: [
      { label: "Registration", month: "July", status: "Upcoming" },
      { label: "Final Submit", month: "December", status: "Upcoming" },
    ],
    benefits: ["Fee reimbursement", "Maintenance allowance"],
    requiredDocuments: ["UP domicile", "Income certificate", "Marksheet", "Fee receipt", "Bank details"],
    applicationProcess: ["Apply on UP portal", "Institute forward", "District verification", "Approval"],
    selectionProcess: ["Category + income verification", "Academic and institutional validation"],
    preparationTips: ["Match details with institute records.", "Submit before institute deadline."],
    faqs: [
      { question: "Can students from private colleges apply?", answer: "Yes, if institute is eligible under portal norms." },
      { question: "Is renewal separate?", answer: "Yes, usually renewal is filed each year." },
    ],
    applicableStates: ["Uttar Pradesh"],
    relatedCollegeSlugs: ["gla-university-mathura", "dr-bhimrao-ambedkar-university", "st-johns-college-agra"],
  },
  {
    name: "Maharashtra Rajarshi Chhatrapati Shahu Maharaj Scholarship",
    slug: "maharashtra-rajarshi-shahu",
    shortDescription: "Tuition assistance for eligible EBC students in Maharashtra.",
    provider: "Government of Maharashtra",
    providerType: "State",
    scholarshipType: "Government",
    level: "UG",
    amountType: "Fee Waiver",
    amountRange: [20000, 100000],
    applicationFee: 0,
    stream: "Professional Courses",
    mode: "Online",
    deadlineMonth: "January",
    renewable: true,
    popular: false,
    eligibility: {
      education: ["Maharashtra resident", "Admission in eligible professional UG course"],
      minPercentage: "As per state rule",
      familyIncome: "Up to state-defined limit",
      stateQuota: "Maharashtra",
      additional: ["Not receiving duplicate scholarship"],
    },
    importantDates: [
      { label: "Application", month: "October-January", status: "Ongoing" },
    ],
    benefits: ["Tuition fee support", "Reduced burden for EBC students"],
    requiredDocuments: ["Domicile", "Income proof", "Admission receipt", "Institute documents"],
    applicationProcess: ["Apply via MahaDBT", "Submit profile", "Institute verification", "Approval"],
    selectionProcess: ["Need and domicile verification", "Eligibility and institute review"],
    preparationTips: ["Ensure income certificate validity period.", "Track MahaDBT status frequently."],
    faqs: [
      { question: "Can PG students apply?", answer: "Depends on scheme variant and latest state guidelines." },
      { question: "Is Aadhaar mandatory?", answer: "Usually required for DBT-enabled disbursement." },
    ],
    applicableStates: ["Maharashtra"],
    relatedCollegeSlugs: ["amity-university-jaipur", "jawaharlal-nehru-university"],
  },
  {
    name: "Fulbright-Nehru Master's Fellowship",
    slug: "fulbright-nehru-masters",
    shortDescription: "International fellowship for outstanding Indian students pursuing master's in the US.",
    provider: "USIEF",
    providerType: "International",
    scholarshipType: "International",
    level: "PG",
    amountType: "Full Funding",
    amountRange: [2500000, 5000000],
    applicationFee: 0,
    stream: "Selected Streams",
    mode: "Online",
    deadlineMonth: "May",
    renewable: false,
    popular: true,
    eligibility: {
      education: ["Equivalent US bachelor's degree", "Strong academic and leadership profile"],
      minPercentage: "High academic merit expected",
      familyIncome: "No strict cap",
      stateQuota: "All India",
      additional: ["English proficiency tests", "SOP and recommendation letters"],
    },
    importantDates: [
      { label: "Application Deadline", month: "May", status: "Upcoming" },
      { label: "Interviews", month: "August", status: "Upcoming" },
    ],
    benefits: ["Tuition", "Living stipend", "Health coverage", "Travel and visa support"],
    requiredDocuments: ["Academic transcripts", "SOP", "LORs", "Test scores", "Resume"],
    applicationProcess: ["Create USIEF profile", "Upload essays and documents", "Interview rounds", "University placement"],
    selectionProcess: ["Holistic merit review", "Leadership and purpose fit", "Interview performance"],
    preparationTips: ["Start SOP and recommendation planning early.", "Build impact-focused profile narrative."],
    faqs: [
      { question: "Is work experience mandatory?", answer: "Preferred in many tracks, check annual notification." },
      { question: "Can final-year students apply?", answer: "Usually degree completion is expected before program start." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["jawaharlal-nehru-university", "amity-university-jaipur", "nalanda-university-delhi"],
  },
  {
    name: "Chevening Scholarship",
    slug: "chevening",
    shortDescription: "Fully-funded UK government scholarship for future global leaders.",
    provider: "UK Government",
    providerType: "International",
    scholarshipType: "International",
    level: "PG",
    amountType: "Full Funding",
    amountRange: [2500000, 5500000],
    applicationFee: 0,
    stream: "All Streams",
    mode: "Online",
    deadlineMonth: "November",
    renewable: false,
    popular: true,
    eligibility: {
      education: ["Bachelor's degree", "Leadership profile"],
      minPercentage: "Competitive academic record",
      familyIncome: "No fixed income cap",
      stateQuota: "All India",
      additional: ["Minimum work experience as per policy", "Offer from eligible UK universities"],
    },
    importantDates: [
      { label: "Application Window", month: "August-November", status: "Ongoing" },
      { label: "Interview", month: "March-April", status: "Upcoming" },
    ],
    benefits: ["Full tuition fee", "Monthly stipend", "Travel costs", "Visa fee support"],
    requiredDocuments: ["Academic transcripts", "Leadership essays", "References", "Admission offers"],
    applicationProcess: ["Online application", "Essay submission", "Interview", "Final nomination"],
    selectionProcess: ["Leadership potential", "Academic and professional merit", "Interview"],
    preparationTips: ["Prepare impact-driven leadership stories.", "Align goals with UK program outcomes."],
    faqs: [
      { question: "Can fresh graduates apply?", answer: "Work experience requirements usually apply." },
      { question: "Is IELTS mandatory?", answer: "Language requirements depend on university admission criteria." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["jawaharlal-nehru-university", "nalanda-university-delhi", "indira-gandhi-national-open-university"],
  },
  {
    name: "National Means-cum-Merit Scholarship (NMMS)",
    slug: "nmms",
    shortDescription: "Support for meritorious students from economically weaker sections at school level.",
    provider: "Department of School Education & Literacy",
    providerType: "Central",
    scholarshipType: "Merit-Based",
    level: "School",
    amountType: "Stipend",
    amountRange: [12000, 12000],
    applicationFee: 0,
    stream: "School",
    mode: "Offline",
    deadlineMonth: "September",
    renewable: true,
    popular: true,
    eligibility: {
      education: ["Class 8 students in government/government-aided schools"],
      minPercentage: "55% in Class 7 (relaxation for reserved categories)",
      familyIncome: "Up to ₹3.5 Lakhs per annum",
      stateQuota: "State-wise quota",
      additional: ["Selection through MAT/SAT"],
    },
    importantDates: [
      { label: "State Notification", month: "August", status: "Upcoming" },
      { label: "Exam", month: "November", status: "Upcoming" },
    ],
    benefits: ["Annual scholarship from Class 9 to 12"],
    requiredDocuments: ["Income certificate", "School bonafide", "Previous marksheet", "Identity proof"],
    applicationProcess: ["Apply via state NMMS portal/school", "Appear for exam", "Complete verification"],
    selectionProcess: ["Merit in MAT/SAT", "Income and category checks"],
    preparationTips: ["Practice basic reasoning and scholastic aptitude.", "Use state-specific NMMS sample papers."],
    faqs: [
      { question: "Can private school students apply?", answer: "Generally not, unless scheme guidelines allow specific category." },
      { question: "How long does scholarship continue?", answer: "From Class 9 to 12 subject to promotion criteria." },
    ],
    applicableStates: ["All India"],
    relatedCollegeSlugs: ["gla-university-mathura", "jawaharlal-nehru-university"],
  },
];

export const getScholarshipBySlug = (slug: string) =>
  scholarships.find((item) => item.slug === slug);

export const getScholarshipFilters = () => {
  const scholarshipTypes = Array.from(new Set(scholarships.map((item) => item.scholarshipType))).sort();
  const levels = Array.from(new Set(scholarships.map((item) => item.level))).sort();
  const providerTypes = Array.from(new Set(scholarships.map((item) => item.providerType))).sort();
  const streams = Array.from(new Set(scholarships.map((item) => item.stream))).sort();
  const modes = Array.from(new Set(scholarships.map((item) => item.mode))).sort();
  const states = Array.from(
    new Set(
      scholarships.flatMap((item) => item.applicableStates),
    ),
  ).sort();

  return { scholarshipTypes, levels, providerTypes, streams, modes, states };
};

export const getRelatedScholarshipColleges = (item: ScholarshipItem): College[] => {
  const bySlug = new Map<string, College>(
    (colleges as College[]).map((college) => [college.slug, college]),
  );

  return item.relatedCollegeSlugs
    .map((slug) => bySlug.get(slug))
    .filter((college): college is College => Boolean(college));
};

export const formatScholarshipAmount = (range: [number, number]) => {
  const [min, max] = range;
  if (min === max) {
    return `₹${min.toLocaleString("en-IN")}`;
  }
  return `₹${min.toLocaleString("en-IN")} - ₹${max.toLocaleString("en-IN")}`;
};
